### ISSUE TITLE
这个项目是next做的博客吗？

### ISSUE THREAD

**Issue by fxwing** [puxiao/puxiao#1]

**Comment by puxiao** [comment]
没有博客，纯粹就一个静态页面。

**Comment by fxwing** [comment]
> 没有博客，纯粹就一个静态页面。

最近在研究rust吗？

**Comment by puxiao** [comment]
是，想着使用 rust 开发 wasm。

**Comment by fxwing** [comment]
> 是，想着使用 rust 开发 wasm。

你都是在哪里学？，然后自己做项目吗？想了解下你学习途径和学习方法

**Comment by puxiao** [comment]
想学什么，
第一：需要一个梯子
第二：看它的官方文档
第三：遇到问题去 github 看源码(仅看相关的代码片段)
第四：技术群里问问题、或者直接问 chatgpt(免费的 3.5 即可)
第五：把你学习过程中遇到的问题，知识点，记录下来，写成文章
(留给将来自己复习看，或者给他人看，提供收获满足感，好更加持续学习)
